---
 -
  Info:         LOAD_LAST_MINUTE
  OutPutName:   Load(last minute)
  Application:  base
  Type:         server
  TimeInterval: 1
  RrdDs:        Load
  RrdDst:       GAUGE
  RrdMethod:    line1
  OutPutCenter: current
  CreatePic:    yes
  Color:        FF0000
  Range:        0,100
  UseApp:       no
  CmdLine:      w |head -1 |awk '{print $(NF-2)}'
 -
  Info:         CONNECT_COUNT
  OutPutName:   CC(last minute)
  Application:  base
  Type:         server
  TimeInterval: 1
  RrdDs:        CC
  RrdDst:       GAUGE
  RrdMethod:    line1
  OutPutCenter: current
  CreatePic:    yes
  Color:        6600CC
  Range:        300,400
  UseApp:       no
  CmdLine:      awk '/^Tcp/ {for(i = 1 ; i < NF ; i++ ){if($i ~/CurrEstab/){ getline;print  $i}}}' /proc/net/snmp
 -
  Info:         BAND_WIDTH_OUT
  OutPutName:   Out(last minute)
  Application:  base
  Type:         server
  TimeInterval: 1
  RrdDs:        Out
  RrdDst:       COUNTER
  RrdMethod:    AREA
  OutPutCenter: current
  CreatePic:    yes
  Color:        00FF00
  Range:        100,400
  UseApp:       yes
  CmdLine:      getBandWidth bond0 out
 -
  Info:         BAND_WIDTH_IN
  OutPutName:   In(last minute)
  Application:  base
  Type:         server
  TimeInterval: 1
  RrdDs:        In
  RrdDst:       COUNTER
  RrdMethod:    LINE1
  OutPutCenter: current
  CreatePic:    yes
  Color:        0000FF
  Range:        100,400
  UseApp:       yes
  CmdLine:      getBandWidth bond0 in

 -
  Info:         PING_LOSS
  OutPutName:   Loss(last minute)
  Application:  base
  Type:         server
  TimeInterval: 1
  RrdDs:        Loss
  RrdDst:       GAUGE
  RrdMethod:    LINE1
  OutPutCenter: current
  CreatePic:    yes
  Color:        FF00FF
  Range:        100,200
  UseApp:       yes
  CmdLine:      getPing `ip route |awk '/default/{print $3}'` |awk '{print $1}'

 -
  Info:         PING_RTT_AVG
  OutPutName:   Rtt_Avg(last minute)
  Application:  base
  Type:         server
  TimeInterval: 1
  RrdDs:        Rtt_Avg
  RrdDst:       GAUGE
  RrdMethod:    LINE1
  OutPutCenter: current
  CreatePic:    yes
  Color:        660000
  Range:        100,200
  UseApp:       yes
  CmdLine:      getPing `ip route |awk '/default/{print $3}'` |awk '{print $3}'

